### ISSUE TITLE
添加LoadUrlBegin事件异常

### ISSUE THREAD

**Issue by Kumhy** [duwenjie15/Raindrops.UI.WebView#1]
```
if (retMap != null && methodInfo.ReturnType != typeof(void))
{
    iLGenerator.Push(eventObj);
    if (retMap.MemberInfo is PropertyInfo propertyInfo)
    {
        iLGenerator.Call(propertyInfo.GetGetMethod(true));
        iLGenerator.Convert(propertyInfo.PropertyType, methodInfo.ReturnType);
    }
    else if (retMap.MemberInfo is FieldInfo fieldInfo)
    {
        iLGenerator.Emit(OpCodes.Ldfld, fieldInfo);
        iLGenerator.Convert(fieldInfo.FieldType, methodInfo.ReturnType);
    }
    iLGenerator.Ret();
}
```

iLGenerator.Convert(propertyInfo.PropertyType, methodInfo.ReturnType);
引发的异常:“System.ArgumentException”(位于 System.Private.CoreLib.dll 中)
这里会引发异常

返回值类型定义错误
Callback 返回值定义的是int
EventArgs 返回值定义的是bool

**Comment by duwenjie15** [comment]
是否提供了调用堆栈或可重现的示例？在正常情况下，所有基本类型转换都是自动的。
Is there a call stack or a reproducible example provided? All basic type conversions are automatic under normal circumstances.

**Comment by Kumhy** [comment]
我是看调试输出发现的
public delegate int mbLoadUrlBeginCallback
是这个回调委托的返回值转换引起的
LoadUrlBeginEventArgs 定义的 返回值类型是bool型，委托定义的是int类型
 public bool Result { get; set; }

**Comment by Kumhy** [comment]
#2 看这里

**Comment by duwenjie15** [comment]
你可以在ConvertMap中看到bool类型与int类型的自动转换,你遇到的问题有可能是特定.Net环境引发的故障，如果方便可以加我的QQ联系。
